---
- name: Copy docker compose file
  ansible.builtin.copy:
    src: "docker-compose.yaml"
    dest: "{{ docker_path }}"
    mode: '0600'

- name: Create init-letsencrypt.sh file from template
  ansible.builtin.template:
    src: "{{ init_letsencrypt_jinja_filename }}"
    dest: "{{ docker_path }}/init-letsencrypt.sh"
    mode: '0744'
