---
- name: Get static db name
  ansible.builtin.shell: >
    set -o pipefail && curl -s -H "X-Vault-Token: {{ vault_token }}"
    -X GET {{ vault_address }}/v1/secret/{{ vault_folder }}/db_name | jq -r ".data.DB_NAME"
  args:
    executable: /bin/bash
  register: static_db_name
  changed_when: false

- name: Set static service db_name var
  ansible.builtin.set_fact:
    db_name: "{{ static_db_name.stdout }}"

- name: Get static db user
  ansible.builtin.shell: >
    set -o pipefail && curl -s -H "X-Vault-Token: {{ vault_token }}"
    -X GET {{ vault_address }}/v1/secret/{{ vault_folder }}/db_user | jq -r ".data.DB_USER"
  args:
    executable: /bin/bash
  register: static_db_user
  changed_when: false

- name: Set static service db_user var
  ansible.builtin.set_fact:
    db_user: "{{ static_db_user.stdout }}"

- name: Get static db password
  ansible.builtin.shell: >
    set -o pipefail && curl -s -H "X-Vault-Token: {{ vault_token }}"
    -X GET {{ vault_address }}/v1/secret/{{ vault_folder }}/db_password | jq -r ".data.DB_PASSWORD"
  args:
    executable: /bin/bash
  register: static_db_password
  changed_when: false

- name: Set static service db_password var
  ansible.builtin.set_fact:
    db_password: "{{ static_db_password.stdout }}"
