---
- name: Copy files to server
  ansible.builtin.include_tasks: "copy_files.yaml"

- name: Get vault token
  ansible.builtin.include_tasks: "get_vault_token.yaml"

- name: Get db secrets
  ansible.builtin.include_tasks: "get_secrets_db.yaml"

- name: Run updated project
  ansible.builtin.include_tasks: "run_docker.yaml"
