version: "3"
services:
  flask_app:
    image: ${FLASK_APP_IMAGE:-registry.gitlab.devsecops.maxmur.info/devsecops/flask_app/flask_app:latest-dev}
    container_name: flask_app
    restart: "always"
    environment:
      - FLASK_APP=dip
      - FLASK_SETTINGS=settings.DevConfig
    volumes:
      - user_images:/app/user_images
      - user_documents:/app/user_documents
      - user_md_files:/app/user_md_files
    expose:
      - "5000"

  db:
    image: registry.gitlab.devsecops.maxmur.info/devsecops/iac/postgres:14.4-alpine
    container_name: db
    restart: "always"
    volumes:
      - psql_volume:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${STATIC_DB_USER:-admin}
      - POSTGRES_PASSWORD=${STATIC_DB_PASS:-admin}
      - POSTGRES_DB=${STATIC_DB_NAME:-static}
    expose:
      - "5432"

volumes:
  psql_volume:
  user_images:
  user_documents:
  user_md_files:
